/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programación.guía.pkg3;

/**
 *
 * @author Bit Store TDF
 */
public class Ejercicio7 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio7
     */
    public Ejercicio7() {
        initComponents();
        Confirmar.setVisible(false);
        NuevaProvincia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Provincias = new javax.swing.JComboBox<>();
        Agregar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        BorrarTodos = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        NuevaProvincia = new javax.swing.JTextField();
        Confirmar = new javax.swing.JButton();
        BorrarEspecifico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ejercicio 7", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Provincia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Provincias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buenos Aires", "Mendoza", "Córdoba", "Chubut", "Tierra del Fuego" }));
        jPanel1.add(Provincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, -1));

        Borrar.setText("Borrar Última");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        jPanel1.add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 110, -1));

        BorrarTodos.setText("Borrar Todos");
        BorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarTodosActionPerformed(evt);
            }
        });
        jPanel1.add(BorrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 110, -1));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 110, -1));
        jPanel1.add(NuevaProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, -1));

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, -1));

        BorrarEspecifico.setText("Borrar Elegida");
        BorrarEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarEspecificoActionPerformed(evt);
            }
        });
        jPanel1.add(BorrarEspecifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        NuevaProvincia.setVisible(true);
        NuevaProvincia.setText("");
        Confirmar.setVisible(true);
    }//GEN-LAST:event_AgregarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        int indice = Provincias.getItemCount()-1;
        Provincias.removeItemAt(indice);

        Confirmar.setVisible(false);
        NuevaProvincia.setVisible(false);
    }//GEN-LAST:event_BorrarActionPerformed

    private void BorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarTodosActionPerformed
        Provincias.removeAllItems();

        Confirmar.setVisible(false);
        NuevaProvincia.setVisible(false);
    }//GEN-LAST:event_BorrarTodosActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Menu obj = new Menu ();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        Provincias.addItem(NuevaProvincia.getText());

        Confirmar.setVisible(false);
        NuevaProvincia.setVisible(false);
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void BorrarEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarEspecificoActionPerformed
        Provincias.removeItemAt(Provincias.getSelectedIndex());
        
        Confirmar.setVisible(false);
        NuevaProvincia.setVisible(false);
    }//GEN-LAST:event_BorrarEspecificoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton BorrarEspecifico;
    private javax.swing.JButton BorrarTodos;
    private javax.swing.JButton Confirmar;
    private javax.swing.JTextField NuevaProvincia;
    private javax.swing.JComboBox<String> Provincias;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
