/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.JOptionPane;

/**
 *
 * @author Bit Store TDF
 */
public class Numeros extends javax.swing.JFrame {

    /**
     * Creates new form Numeros
     */
    public Numeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Etiqueta3 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        Menor = new javax.swing.JButton();
        Promedio = new javax.swing.JButton();
        Etiqueta1 = new javax.swing.JLabel();
        Etiqueta2 = new javax.swing.JLabel();
        Mayor = new javax.swing.JButton();
        Numero3 = new javax.swing.JTextField();
        Numero1 = new javax.swing.JTextField();
        Numero2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 315));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Etiqueta3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Etiqueta3.setText("Número 3");
        jPanel1.add(Etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        Volver.setBackground(new java.awt.Color(204, 204, 204));
        Volver.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, -1));

        Menor.setBackground(new java.awt.Color(204, 204, 204));
        Menor.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Menor.setText("Menor");
        Menor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenorActionPerformed(evt);
            }
        });
        jPanel1.add(Menor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 100, -1));

        Promedio.setBackground(new java.awt.Color(204, 204, 204));
        Promedio.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Promedio.setText("Promedio");
        Promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromedioActionPerformed(evt);
            }
        });
        jPanel1.add(Promedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, -1));

        Etiqueta1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Etiqueta1.setText("Número 1");
        jPanel1.add(Etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Etiqueta2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Etiqueta2.setText("Número 2");
        jPanel1.add(Etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Mayor.setBackground(new java.awt.Color(204, 204, 204));
        Mayor.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Mayor.setText("Mayor");
        Mayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MayorActionPerformed(evt);
            }
        });
        jPanel1.add(Mayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, -1));
        jPanel1.add(Numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        Numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero1ActionPerformed(evt);
            }
        });
        jPanel1.add(Numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 150, -1));
        jPanel1.add(Numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenorActionPerformed
        
        String n1,n2,n3;
        float num1,num2,num3;
        
        if (Numero1.getText().isEmpty()==true && Numero2.getText().isEmpty()==true && Numero3.getText().isEmpty()==true)    JOptionPane.showMessageDialog(rootPane, "Ingrese valores en al menos un campo");
        
        else
        {
            if (Numero1.getText().isEmpty()==true)  Numero1.setText("0");
            if (Numero2.getText().isEmpty()==true)  Numero2.setText("0");
            if (Numero3.getText().isEmpty()==true)  Numero3.setText("0");
                
            n1=Numero1.getText();
            n2=Numero2.getText();
            n3=Numero3.getText();
        
            num1=Float.parseFloat(n1);
            num2=Float.parseFloat(n2);
            num3=Float.parseFloat(n3);
        
            if (num1==0)    num1=999999999.99999999999999999f;
            if (num2==0)    num2=999999999.99999999999999999f;
            if (num3==0)    num3=999999999.99999999999999999f;
        
            if (num1<=num2 && num1<=num3)   JOptionPane.showMessageDialog(rootPane, "El menor número ingresado es: "+num1);
            if (num2<=num1 && num2<=num3)   JOptionPane.showMessageDialog(rootPane, "El menor número ingresado es: "+num2);
            if (num3<=num2 && num3<=num1)   JOptionPane.showMessageDialog(rootPane, "El menor número ingresado es: "+num3);          
        }
    }//GEN-LAST:event_MenorActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Menu obj = new Menu();
        obj.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_VolverActionPerformed

    private void PromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromedioActionPerformed
        String n1,n2,n3;
        float num1,num2,num3,c1;
        float prom;
        
        if (Numero1.getText().isEmpty()==true && Numero2.getText().isEmpty()==true && Numero3.getText().isEmpty()==true)    JOptionPane.showMessageDialog(rootPane,"Ingrese valores en al menos un campo");
        
        else
        {
            c1=3;
            if (Numero1.getText().isEmpty()==true) 
            {
                Numero1.setText("0");
            }
        
            if (Numero2.getText().isEmpty()==true) 
            {
                Numero2.setText("0");
            }
        
            if (Numero3.getText().isEmpty()==true) 
            {
                Numero3.setText("0");
            }
        
            n1=Numero1.getText();
            n2=Numero2.getText();
            n3=Numero3.getText();
        
            num1=Float.parseFloat(n1);
            num2=Float.parseFloat(n2);
            num3=Float.parseFloat(n3);

            if (num1==0)    c1--;
            if (num2==0)    c1--;
            if (num3==0)    c1--;
            
            prom=(num1+num2+num3)/c1;
            
            JOptionPane.showMessageDialog(rootPane, "El promedio de los números es "+prom);
        }            
    }//GEN-LAST:event_PromedioActionPerformed

    private void MayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MayorActionPerformed
        String n1,n2,n3;
        float num1,num2,num3;
        
        if (Numero1.getText().isEmpty()==true && Numero2.getText().isEmpty()==true && Numero3.getText().isEmpty()==true)    JOptionPane.showMessageDialog(rootPane,"Ingrese valores en al menos un campo"); 
        
        else
        {
            if (Numero1.getText().isEmpty()==true)  Numero1.setText("0");
            if (Numero2.getText().isEmpty()==true)  Numero2.setText("0");
            if (Numero3.getText().isEmpty()==true)  Numero3.setText("0");
                
            n1=Numero1.getText();
            n2=Numero2.getText();
            n3=Numero3.getText();
        
            num1=Float.parseFloat(n1);
            num2=Float.parseFloat(n2);
            num3=Float.parseFloat(n3);
            
            if (num1==0)    num1=-999999999.99999999999999999f;
            if (num2==0)    num2=-999999999.99999999999999999f;
            if (num3==0)    num3=-999999999.99999999999999999f;
            
            if (num1>=num2 && num1>=num3) JOptionPane.showMessageDialog(rootPane,"El mayor número ingresado es: "+num1);
            if (num2>=num1 && num2>=num3) JOptionPane.showMessageDialog(rootPane,"El mayor número ingresado es: "+num2);
            if (num3>=num2 && num3>=num1) JOptionPane.showMessageDialog(rootPane,"El mayor número ingresado es: "+num3);
        }
        
    }//GEN-LAST:event_MayorActionPerformed

    private void Numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Numero1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiqueta1;
    private javax.swing.JLabel Etiqueta2;
    private javax.swing.JLabel Etiqueta3;
    private javax.swing.JButton Mayor;
    private javax.swing.JButton Menor;
    private javax.swing.JTextField Numero1;
    private javax.swing.JTextField Numero2;
    private javax.swing.JTextField Numero3;
    private javax.swing.JButton Promedio;
    private javax.swing.JButton Volver;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
