/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author Bit Store TDF
 */
public class Saludo extends javax.swing.JFrame {

    /**
     * Creates new form Saludo
     */
    public Saludo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Etiqueta = new javax.swing.JLabel();
        Azul = new javax.swing.JButton();
        Saludo = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        Rojo = new javax.swing.JButton();
        Verde = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Cuadro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saludo");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Etiqueta.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Etiqueta.setText("Nombre");
        jPanel1.add(Etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        Azul.setBackground(new java.awt.Color(204, 204, 204));
        Azul.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Azul.setText("Azul");
        Azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AzulActionPerformed(evt);
            }
        });
        jPanel1.add(Azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 70, -1));

        Saludo.setBackground(new java.awt.Color(204, 204, 204));
        Saludo.setFont(new java.awt.Font("Sitka Subheading", 3, 18)); // NOI18N
        Saludo.setText("Saludo");
        Saludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaludoActionPerformed(evt);
            }
        });
        jPanel1.add(Saludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, -1));

        Volver.setBackground(new java.awt.Color(204, 204, 204));
        Volver.setFont(new java.awt.Font("Sitka Subheading", 3, 18)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 100, -1));

        Rojo.setBackground(new java.awt.Color(204, 204, 204));
        Rojo.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Rojo.setText("Rojo");
        Rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RojoActionPerformed(evt);
            }
        });
        jPanel1.add(Rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 70, -1));

        Verde.setBackground(new java.awt.Color(204, 204, 204));
        Verde.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Verde.setText("Verde");
        Verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerdeActionPerformed(evt);
            }
        });
        jPanel1.add(Verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 70, -1));

        Limpiar.setBackground(new java.awt.Color(204, 204, 204));
        Limpiar.setFont(new java.awt.Font("Sitka Subheading", 3, 18)); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 100, -1));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 150, 30));

        Cuadro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cuadro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaludoActionPerformed

        if (Nombre.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un nombre");
        }
        
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Bienvenido, "+Nombre.getText());
            Cuadro.setText(Nombre.getText());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_SaludoActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        Nombre.setText("");
        Etiqueta.setForeground(Color.black);
        Nombre.setForeground(Color.black);
        Cuadro.setForeground(Color.black);
        Cuadro.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Menu obj = new Menu();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void RojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RojoActionPerformed
        Nombre.setForeground(Color.red);
        Etiqueta.setForeground(Color.red);
        Cuadro.setForeground(Color.red);
    }//GEN-LAST:event_RojoActionPerformed

    private void VerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerdeActionPerformed
        Nombre.setForeground(Color.green);
        Etiqueta.setForeground(Color.green);
        Cuadro.setForeground(Color.green);
    }//GEN-LAST:event_VerdeActionPerformed

    private void AzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AzulActionPerformed
        Nombre.setForeground(Color.blue);
        Etiqueta.setForeground(Color.blue);
        Cuadro.setForeground(Color.blue);
    }//GEN-LAST:event_AzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saludo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Azul;
    private javax.swing.JLabel Cuadro;
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton Rojo;
    private javax.swing.JButton Saludo;
    private javax.swing.JButton Verde;
    private javax.swing.JButton Volver;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
