/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.JOptionPane;

/**
 *
 * @author Bit Store TDF
 */
public class Triangulo extends javax.swing.JFrame {

    /**
     * Creates new form Triangulo
     */
    public Triangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Etiqueta3 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Perimetro = new javax.swing.JButton();
        Etiqueta1 = new javax.swing.JLabel();
        Etiqueta2 = new javax.swing.JLabel();
        Superficie = new javax.swing.JButton();
        LadoC = new javax.swing.JTextField();
        LadoA = new javax.swing.JTextField();
        LadoB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 315));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Etiqueta3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Etiqueta3.setText("Lado C");
        jPanel1.add(Etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        Volver.setBackground(new java.awt.Color(204, 204, 204));
        Volver.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, -1));

        Limpiar.setBackground(new java.awt.Color(204, 204, 204));
        Limpiar.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 100, -1));

        Perimetro.setBackground(new java.awt.Color(204, 204, 204));
        Perimetro.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Perimetro.setText("Perímetro");
        Perimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimetroActionPerformed(evt);
            }
        });
        jPanel1.add(Perimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, -1));

        Etiqueta1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Etiqueta1.setText("Lado A");
        jPanel1.add(Etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Etiqueta2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Etiqueta2.setText("Lado B");
        jPanel1.add(Etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Superficie.setBackground(new java.awt.Color(204, 204, 204));
        Superficie.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        Superficie.setText("Superficie");
        Superficie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuperficieActionPerformed(evt);
            }
        });
        jPanel1.add(Superficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, -1));
        jPanel1.add(LadoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));
        jPanel1.add(LadoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 150, -1));
        jPanel1.add(LadoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Menu obj = new Menu();
        obj.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_VolverActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed

        LadoA.setText("");
        LadoB.setText("");
        LadoC.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void PerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimetroActionPerformed
        String l1,l2,l3;
        float ladoA,ladoB,ladoC;
        float per;

        if (LadoA.getText().isEmpty()==true || LadoB.getText().isEmpty()==true || LadoC.getText().isEmpty()==true)    JOptionPane.showMessageDialog(rootPane,"Ingrese valores en todos los campos");

        else
        {
            l1=LadoA.getText();
            l2=LadoB.getText();
            l3=LadoC.getText();
            
            ladoA=Float.parseFloat(l1);
            ladoB=Float.parseFloat(l2);
            ladoC=Float.parseFloat(l3);
            
            per=ladoA+ladoB+ladoC;
            
            JOptionPane.showMessageDialog(rootPane, "El perímetro del triángulo es de: "+per);
        }
        
    }//GEN-LAST:event_PerimetroActionPerformed

    private void SuperficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuperficieActionPerformed
        String l1,l2,l3;
        float ladoA,ladoB,ladoC;
        float sup;

        if (LadoA.getText().isEmpty()==true || LadoB.getText().isEmpty()==true || LadoC.getText().isEmpty()==true)    JOptionPane.showMessageDialog(rootPane,"Ingrese valores en todos los campos");
        
        else
        {
            l1=LadoA.getText();
            l2=LadoB.getText();
            l3=LadoC.getText();
            
            ladoA=Float.parseFloat(l1);
            ladoB=Float.parseFloat(l2);
            ladoC=Float.parseFloat(l3);
            
            //VER COMO SACAR CON TEOREMAS SENO Y COSENO
            //OPCION 2: HACER DOS VENTANAS NUEVAS, CADA UNA PIDIENDO DATOS DISTINTOS PARA GENERAR EL PERIMETRO O EL AREA
            
        }
        
    }//GEN-LAST:event_SuperficieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiqueta1;
    private javax.swing.JLabel Etiqueta2;
    private javax.swing.JLabel Etiqueta3;
    private javax.swing.JTextField LadoA;
    private javax.swing.JTextField LadoB;
    private javax.swing.JTextField LadoC;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Perimetro;
    private javax.swing.JButton Superficie;
    private javax.swing.JButton Volver;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
